name: frontend CI - deploy on heroku
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Heroku-LIVE
      url: https://reasearch-management-sliit-f.herokuapp.com/
    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "reasearch-management-sliit-f" 
          heroku_email: "researchprojectsliit@gmail.com"
